server:
  port: 8181

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/greenplan}
    username: ${DB_USER:gp_user}
    password: ${DB_PASS:gp_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:com/greenplan/knowledge/db/migration
    baseline-on-migrate: true

app:
  storage:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access: ${MINIO_ACCESS_KEY:minioadmin}
    secret: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:greenplan}
  ollama:
    baseUrl: ${OLLAMA_BASE_URL:http://localhost:11434}
    embedModel: ${OLLAMA_EMBED_MODEL:mxbai-embed-large}
  openai:
    baseUrl: ${CLOUD_LLM_BASE_URL:https://api.openai.com/v1}
    model: ${CLOUD_LLM_MODEL:gpt-4o-mini}
    apiKey: ${OPENAI_API_KEY:changeme}