server:
  port: 8181
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath*:../knowledge/src/main/resources/db/migration

app:
  storage:
    endpoint: ${MINIO_ENDPOINT}
    access: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}
  ollama:
    baseUrl: ${OLLAMA_BASE_URL}
    embedModel: ${OLLAMA_EMBED_MODEL}
  openai:
    baseUrl: ${CLOUD_LLM_BASE_URL}
    model: ${CLOUD_LLM_MODEL}
    apiKey: ${OPENAI_API_KEY}